Сustom options
spatie/docker pull request #20
Opened 2020-11-23 12:19 UTC by exileed

Added ->setOption(); method for custom options.

Thanks.

2020-11-23 12:41 UTC, freekmurze requested changes
Could you also add a new method `setOptions` which accepts an array? Also update the readme and tests for that one.

Thanks for your work on this.

2020-11-23 12:41 UTC, freekmurze commented on src/OptionMapping.php
> +class OptionMapping
Rename this to `Option`

2020-11-23 12:41 UTC, freekmurze commented on src/OptionMapping.php
> +    private string $optionName;
Change `private` to `protected`

2020-11-23 12:41 UTC, freekmurze commented on src/OptionMapping.php
> +     * ArgumentMapping constructor.
Remove this unneeded comment

2020-11-23 16:15 UTC, exileed commented
> 
> 
> Could you also add a new method `setOptions` which accepts an array? Also update the readme and tests for that one.
> 
> Thanks for your work on this.

Done.

2020-11-24 07:33 UTC, freekmurze requested changes
Nearly there!

Could you also document the `setOptions` method in the readme?

2020-11-24 07:33 UTC, freekmurze commented on src/DockerContainer.php
> +     * @param array $options
This comment doesn't bring any value, remove it

2020-11-24 07:33 UTC, freekmurze commented on src/Option.php
> +     * @var int|string
For consistency use a one-line docblock

2021-03-25 11:03 UTC, closed without merging